/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 6.0.0   2016-09-29

The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include "stm32l1xx.h"
#include <math.h>
/* Private typedef */
/* Private define  */
/* Private macro */
/* Private variables */
/* Private function prototypes */
/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/


int main(void)
{
	int BUTTON;

	RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOA, ENABLE);
    RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOC, ENABLE);

    GPIO_InitTypeDef strukturaA;
    strukturaA.GPIO_Mode = GPIO_Mode_OUT;
    strukturaA.GPIO_OType = GPIO_OType_PP;
    strukturaA.GPIO_PuPd = GPIO_PuPd_UP;
    strukturaA.GPIO_Pin = GPIO_Pin_5;
    strukturaA.GPIO_Speed = GPIO_Speed_40MHz;
    GPIO_Init(GPIOA, &strukturaA);

    GPIO_InitTypeDef strukturaC;
    strukturaC.GPIO_Mode = GPIO_Mode_IN;
    strukturaC.GPIO_PuPd = GPIO_PuPd_NOPULL;
    strukturaC.GPIO_OType = GPIO_OType_PP;
    strukturaC.GPIO_Pin = GPIO_Pin_13;
    GPIO_Init(GPIOC, &strukturaC);

    GPIOA->MODER |= (0b01) << (5*2);
    GPIOA->OTYPER &= ~((uint16_t)(1<<5));
    GPIOA->PUPDR |= (0b01) << (5*2);
    GPIOA->OSPEEDR |= (0b11) << (5*2);
    GPIOC->MODER |= (0b00) << (13*2);
    GPIOC->OTYPER &= ~((uint16_t)(1<<13));
    GPIOC->PUPDR |= (0b00) << (13*2);

/////////   Uloha 1   /////////////////////////////////////////////
/*	while(1){
		GPIOA->ODR |= 0b0000000000100000; //LEDka svieti
		GPIOA->ODR &= ~(0b0000000000100000); //LEDka nesvieti
		GPIOA->BSRRL |= ((uint16_t)(1<<5)); //LEDka svieti
		GPIOA->BSRRH |= ((uint16_t)(1<<5)); //LEDka nesvieti

		GPIOA->ODR ^= (1<<5); //prepinam - mala by byt vypnuta
		GPIOA->ODR ^= (1<<5); //prepinam - mala by svietit
		GPIOA->ODR ^= (1<<5); // prepinam - vypnuta
		GPIOA->ODR ^= (1<<5); // prepinam - svieti
	}*/
////////////////////////////////////////////////////////////////////

/////////   Uloha 2   /////////////////////////////////////////////
  	/*while(1){
    	i++;
  	 if ((GPIOC->IDR & (0b0010000000000000)) == 0)
  	   BUTTON = 1;
  	 else if ((GPIOC->IDR & (0b0010000000000000)) == (pow(2,13)))
  	   BUTTON = 0;
    }
/////////////////////////////////////////////////////////////////*/

///////////// Uloha 1 s pouzitim kniznice //////////////////////
  /*while (1){
	  GPIO_ToggleBits(GPIOA, GPIO_Pin_5);
  }*/
//////////////////////////////////////////////////////////////////

//////////////// Uloha 2 s pouzitim kniznice ////////////
/*while(1){
	  if ((GPIO_ReadInputDataBit(GPIOC, GPIO_Pin_13)) == 0){
		  BUTTON = 1;
	  }
	  else if ((GPIO_ReadInputDataBit(GPIOC, GPIO_Pin_13)) == 1 ){
		  BUTTON = 0;
	  }
  }*/
//////////////////////////////////////////////////////////////////////

///////////////    Uloha 3, prva cast  ////////////////////////////////////
    /*int i;
	int j;

    while(1){
    	i = 1;
    	j = 1;
    	GPIOA->ODR ^= (1<<5); //LEDka svieti
    	for ( i=1; i<= 500; i++){
    		for ( j=1; j<= 500; j++){
    			}
    		}
    	GPIOA->ODR ^= (1<<5); //LEDka nesvieti
    	i = 1;
    	j = 1;
    	for ( i=1; i<= 500; i++){
    		for ( j=1; j<= 500; j++){
    			}
    		}
    }*/
/////////////////////////////////////////////////////

///////////////    Uloha 3, druha cast  ////////////////////////////////////
      /*while(1){
          	if ((GPIOC->IDR & (0b0010000000000000)) == 0)
        		 GPIOA->ODR |= 0b0000000000100000; //LEDka svieti
        	 else if ((GPIOC->IDR & (0b0010000000000000)) == (pow(2,13)))
        		 GPIOA->ODR &= ~(0b0000000000100000); //LEDka nesvieti
          }*/
/////////////////////////////////////////////////////////////

///////////////// Uloha 3, tretia cast //////////////////////////////////
 /* int i, j = 0;
    while(1){
    	 for (i = 0;i<=5;i++){
    		 if ((GPIOC->IDR & (0b0010000000000000)) == 0){
    			 i++;
    	 	  	 if (i>3){
    	 	  		 BUTTON = 1;
    	 	  	 }
    	 	 }
    	 }
    	 if (BUTTON == 1){
    		 if ((GPIOC->IDR & (0b0010000000000000)) == (pow(2,13))){
    			 j++;
    			 if (j>5){
    				 GPIOA->ODR ^= (1<<5);
    				 BUTTON = 0;
    			 }
    		 }
    	 }
    }*/
///////////////////////////////////////////////////////////////////

///////////  Uloha 3 - pouzita kniznica, cast 1 ////////////////////
    /*int i, j;
    while(1){
    	GPIO_ToggleBits(GPIOA, GPIO_Pin_5);
    	for (int i=1; i<= 500; i++){
    		for (int j=1; j<= 500; j++){
    		}
    	}
    }*/
//////////////////////////////////////////////////////////////////////

///////////  Uloha 3 - pouzita kniznica, cast 2 ////////////////////
   /* while(1){
    	if ((GPIO_ReadInputDataBit(GPIOC, GPIO_Pin_13)) == 0)
    		GPIO_SetBits(GPIOA, GPIO_Pin_5); //LEDka svieti
    	if ((GPIO_ReadInputDataBit(GPIOC, GPIO_Pin_13)) == 1)
    		GPIO_ResetBits(GPIOA, GPIO_Pin_5); //LEDka nesvieti
    }*/
//////////////////////////////////////////////////////////////////////

///////////  Uloha 3 - pouzita kniznica, cast 3 ////////////////////
    int i, j = 0;
        while(1){
        	 for (i = 0;i<=5;i++){
        		 if ((GPIO_ReadInputDataBit(GPIOC, GPIO_Pin_13)) == 0){
        			 i++;
        	 	  	 if (i>3){
        	 	  		 BUTTON = 1;
        	 	  	 }
        	 	 }
        	 }
        	 if (BUTTON == 1){
        		 if ((GPIO_ReadInputDataBit(GPIOC, GPIO_Pin_13)) == 1){
        			 j++;
        			 if (j>5){
        				 GPIO_ToggleBits(GPIOA, GPIO_Pin_5);
        				 BUTTON = 0;
        			 }
        		 }
        	 }
        }
/////////////////////////////////////////////////////////////////////
  return 0;
}

#ifdef  USE_FULL_ASSERT

/**
  * @brief  Reports the name of the source file and the source line number
  *   where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t* file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

  /* Infinite loop */
  while (1)
  {
  }
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}



/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}

